### ISSUE TITLE
feat: just remove nag messages and owls without randomizing.

### ISSUE THREAD

**Issue by twoco** [daid/LADXR#35]
Hi, great tool. But I would like to know how to remove the pesky talking owls that appears e.g. on find my sword. worm key, etc.
Also remove the nag messages. All this stuff already works. But I want a solution without randomizer. Just keep all as original, just remove the annoying parts (owls, nag msg). Also no other brands (additional menu text like seed. just original)
In my case I want to adapt this to a different language version. I think I could compare the changed bytes by a hex editor. ^^

We could make the randomizer optional (enabled by default). I see the "Show nag messages" option. But no "remove owls" option. I viewed the code and found something about. But I'm not experienced enought to adapt this. What do you think? Removing the owls and nag messages: Are these just a few bytes to change? Or a bit more complex?

**Comment by daid** [comment]
https://github.com/daid/LADX-Hackers-Toolbox
Is the tooling behind LADXR split of to be used to be used as a rom hack tooling.

Removing the owl events just removes all owl event entities from the game. Which changes a lot of bytes due to how that is stored. But using the toolbox should make that a question of just going over the right rooms and deleting those entities.
